### ISSUE TITLE
incentives_address missing for testnets

### ISSUE THREAD

**Issue by Buckram123** [astroport-fi/astroport-changelog#4]
We would like to use a script for getting addresses of incentives from this repo, but testnets missing those addresses
> seems changelog repo missing these addresses 

(@epanchee, from astroport dev telegram chat)

**Comment by donovansolms** [comment]
Hi @Buckram123 
Testnet addresses have been added for all the chains we're deployed on as `incentives_address`

**Comment by Buckram123** [comment]
> Hi @Buckram123 Testnet addresses have been added for all the chains we're deployed on as `incentives_address`

Nice, thanks
